/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Reze(props) {
  const { nodes, materials } = useGLTF("/Reze.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0.geometry}
        material={materials.Material_0}
        position={[1.186, 1.29, 1.62]}
        rotation={[0, -1.063, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Reze.glb");
